apiVersion: apps/v1
kind: Deployment
metadata:
  name:gunser
spec:
  replicas: 1
  selector:
    matchLabels:
      app:gunser
  template:
    metadata:
      labels:
        app:gunser
    spec:
      containers:
      - image: okteto.dev/gunser:latest
        name:gunser
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e9433da4-47fc-41a1-8080-f72ac8cfd80f"
        - name: Vless_Path
          value: "/vl33bbs5"
        - name: Vmess_UUID
          value: "e9433da4-47fc-41a1-8080-f72ac8cfd80f"
        - name: Vmess_Path
          value: "/vm66vv3346"
        - name: Share_Path
          value: "/v2link"
